// Generated by gohack; DO NOT EDIT.
module github.com/jtwatson/twiml

go 1.23.2

retract [v1.0.0, v1.2.2]

require (
	github.com/pkg/errors v0.9.1
	github.com/ttacon/libphonenumber v1.2.1
	go.opencensus.io v0.24.0
)

require (
	github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/ttacon/builder v0.0.0-20170518171403-c099f663e1c2 // indirect
	google.golang.org/protobuf v1.33.0 // indirect
)
