// Generated by gohack; DO NOT EDIT.
module github.com/jtwatson/twiml

go 1.12

require (
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/hashicorp/golang-lru v0.5.1 // indirect
	github.com/pkg/errors v0.8.1
	github.com/ttacon/builder v0.0.0-20170518171403-c099f663e1c2 // indirect
	github.com/ttacon/libphonenumber v1.0.1
	go.opencensus.io v0.21.0
	golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c // indirect
)
